# Generated by Django 3.2.22 on 2025-03-03 23:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaTecnologica',
            fields=[
                ('id_area_tecnologica', models.AutoField(primary_key=True, serialize=False)),
                ('area_tecnologica', models.CharField(max_length=100, verbose_name='Área Tecnológica')),
            ],
            options={
                'verbose_name': 'Área Tecnológica',
                'verbose_name_plural': 'Áreas Tecnológicas',
                'ordering': ['area_tecnologica'],
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id_colaborador', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('dt_nascimento', models.DateField(verbose_name='Data de Nascimento')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Financiador',
            fields=[
                ('id_financiador', models.AutoField(primary_key=True, serialize=False)),
                ('financiador', models.CharField(max_length=100, verbose_name='Financiador')),
            ],
            options={
                'verbose_name': 'Financiador',
                'verbose_name_plural': 'Financiadores',
                'ordering': ['financiador'],
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id_projeto', models.AutoField(primary_key=True, serialize=False)),
                ('projeto', models.CharField(max_length=100, verbose_name='Nome do Projeto')),
                ('coordenador', models.CharField(max_length=100, verbose_name='Coordenador')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('inicio_vigencia', models.DateField(verbose_name='Início da Vigência')),
                ('fim_vigencia', models.DateField(verbose_name='Fim da Vigência')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor')),
                ('qtd_membros', models.IntegerField(default=0, editable=False, verbose_name='Quantidade de Membros')),
                ('equipe', models.ManyToManyField(blank=True, related_name='projetos', to='core.Colaborador', verbose_name='Equipe')),
                ('id_area_tecnologica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projetos', to='core.areatecnologica', verbose_name='Área Tecnológica')),
                ('id_financiador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projetos', to='core.financiador', verbose_name='Financiador')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-inicio_vigencia'],
            },
        ),
    ]
